apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
      # Add an annotation to force a restart
      annotations:
        kubernetes.io/change-cause: "Fixed mutex poisoning issues - deployed from source"
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: product-service
        # Use a specific version instead of latest
        image: ghcr.io/azure-samples/aks-store-demo/product-service:latest
        imagePullPolicy: Always  # Force image pull
        ports:
        - containerPort: 3002
        env: 
        - name: AI_SERVICE_URL
          value: "http://ai-service:5001/"
        # Add thread management environment variables
        - name: RUST_BACKTRACE
          value: "1"
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 200Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
